name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build -t evansantos/dorker -f Dockerfile . 
      - name: docker npm test
        run: |
          docker run -e CI=true evansantos/dorker npm run test
     
